version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  frontend:
    container_name: accounts-frontend
    build:
      context: .
      dockerfile: ./packages/accounts-frontend/development.Dockerfile
    # command: npm install && npm run build && npm run generate && npm run dev --stream --scope=@xarples/accounts-frontend
    restart: on-failure
    ports:
      - 5000:5000
    environment:
      HOST: 0.0.0.0
      PORT: 5000
      NODE_ENV: development
      GRPC_SERVER_HOST: server
      GRPC_SERVER_PORT: 5001
    volumes:
      - ./packages/accounts-fastify-plugins:/usr/src/accounts/packages/accounts-fastify-plugins
      - ./packages/accounts-client:/usr/src/accounts/packages/accounts-client
      - ./packages/accounts-frontend:/usr/src/accounts/packages/accounts-frontend
      - ./packages/accounts-proto-loader:/usr/src/accounts/packages/accounts-proto-loader
      - ./packages/accounts-utils:/usr/src/accounts/packages/accounts-utils
      - /usr/src/accounts/node_modules
    depends_on:
      - server

  server:
    container_name: accounts-server
    build:
      context: .
      dockerfile: ./packages/accounts-server/development.Dockerfile
    restart: on-failure
    ports:
      - 5001:5001
    environment:
      HOST: 0.0.0.0
      PORT: 5001
      NODE_ENV: development
      DATABASE_URL: postgresql://app:app@postgres:5432/app?schema=public
    volumes:
      - ./packages/accounts-db:/usr/src/accounts/packages/accounts-db
      - ./packages/accounts-proto-loader:/usr/src/accounts/packages/accounts-proto-loader
      - ./packages/accounts-server:/usr/src/accounts/packages/accounts-server
      - ./packages/accounts-service:/usr/src/accounts/packages/accounts-service
      - ./packages/accounts-utils:/usr/src/accounts/packages/accounts-utils
      - /usr/src/accounts/node_modules
    depends_on:
      - postgres

  developers:
    container_name: developers-frontend
    build:
      context: .
      dockerfile: ./packages/developers-frontend/development.Dockerfile
    restart: on-failure
    ports:
      - 5002:5002
    environment:
      HOST: 0.0.0.0
      PORT: 5002
      NODE_ENV: development
      GRPC_SERVER_HOST: server
      GRPC_SERVER_PORT: 5001
    volumes:
      - ./packages/accounts-fastify-plugins:/usr/src/accounts/packages/accounts-fastify-plugins
      - ./packages/accounts-client:/usr/src/accounts/packages/accounts-client
      - ./packages/developers-frontend:/usr/src/accounts/packages/developers-frontend
      - ./packages/accounts-proto-loader:/usr/src/accounts/packages/accounts-proto-loader
      - ./packages/accounts-utils:/usr/src/accounts/packages/accounts-utils
      - /usr/src/accounts/node_modules
    depends_on:
      - server
