export { default as fastifyAuth } from './fastify-auth'
export { default as fastifyNuxt } from './fastify-nuxt'
export { default as fastifyOauth } from './fastify-oauth'
export * from './fastify-oauth'
export { default as fastifySession } from './fastify-session'
export { default as fastifyUser } from './fastify-user'
